### ISSUE TITLE
Error occurred when compiling the sample with ubuntu1804: json_pointer.h:46:18: error: ‘std::enable_if_t’ has not been declared

### ISSUE THREAD

**Issue by yyt6801** [bytedance/sonic-cpp#25]
Error occurred when compiling the sample with ubuntu1804:
./include/sonic/dom/json_pointer.h:46:18: error: ‘std::enable_if_t’ has not been declared              
std::enable_if_t<std::is_integral<T>::value, bool> = true>

Thanks for such an excellent open source project repository of ByteDance , and looking forward to better development, Expect to support more platforms, such as msvc

**Comment by liuq19** [comment]
Are you use c++11 here? because enable_if_t is a c++14 feature.
We will fix this problem to support c++11.

**Comment by liuq19** [comment]
Thanks for your suggestions.  arm64 and msvc will be supported in the future.

**Comment by yyt6801** [comment]
There is no problem with the latest test example. Thanks for solving!
