### ISSUE TITLE
find member from object by map seems slower than list

### ISSUE THREAD

**Issue by yanminhui** [bytedance/sonic-cpp#30]
## What happened

`UpdateNodeLazy` updates object by `CreateMap` may be slower than list.

```.cpp
template <typename NodeType, typename Allocator>
static inline SonicError UpdateNodeLazy(NodeType &target, NodeType &source,
                                        Allocator &alloc) {
  ParseResult ret;
  SonicError err = kErrorNone;
  // check the raw type
  if (target.IsRaw() && *target.GetRaw().data() == '{') {
    ret = ParseLazy(target, target.GetRaw(), alloc);
  }
  if (source.IsRaw() && *source.GetRaw().data() == '{') {
    ret = ParseLazy(source, source.GetRaw(), alloc);
  }
  if (ret.Error()) {
    return ret.Error();
  }
  // update the object type
  if (!target.IsObject() || !source.IsObject() || target.Empty()) {
    target = std::move(source);
    return kErrorNone;
  }
  target.CreateMap(alloc);
  auto source_begin = source.MemberBegin(), source_end = source.MemberEnd();
  for (auto iter = source_begin; iter != source_end; iter++) {
    StringView key = iter->name.GetStringView();
    auto match = target.FindMember(key);
    if (match == target.MemberEnd()) {
      target.AddMember(key, iter->value, alloc);
    } else {
      err = UpdateNodeLazy(match->value, iter->value, alloc);
      if (err) return err;
    }
  }
  return err;
}
```

and 

https://github.com/bytedance/sonic-cpp/blob/fc7545be5c393f0b43494111ea068e8fbac77065/docs/usage.md?plain=1#L48-L81

## Benchmark

```.bash
Run on (8 X 24.1208 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB
  L1 Instruction 128 KiB
  L2 Unified 4096 KiB (x8)
Load Average: 1.45, 1.42, 1.46
-------------------------------------------------------------------
Benchmark                         Time             CPU   Iterations
-------------------------------------------------------------------
BM_GetObjectByIterate/2        13.8 ns         13.8 ns     42653797
BM_GetObjectByIterate/10        130 ns          130 ns      5593199
BM_GetObjectByIterate/18        416 ns          416 ns      1648711
BM_GetObjectByIterate/26        949 ns          949 ns       733822
BM_GetObjectByIterate/32       1515 ns         1515 ns       463346
BM_GetObjectByIterate/48       3643 ns         3643 ns       189418
BM_GetObjectByIterate/64       6877 ns         6877 ns       100505
BM_GetObjectByIterate/80      11081 ns        11081 ns        62114
BM_GetObjectByIterate/96      16769 ns        16769 ns        41888
BM_GetObjectByMap/2            86.6 ns         86.6 ns      8092766
BM_GetObjectByMap/10            566 ns          566 ns      1207292
BM_GetObjectByMap/18           1067 ns         1067 ns       637047
BM_GetObjectByMap/26           1651 ns         1651 ns       410442
BM_GetObjectByMap/32           2151 ns         2151 ns       320698
BM_GetObjectByMap/48           3475 ns         3475 ns       196641
BM_GetObjectByMap/64           5065 ns         5065 ns       138496
BM_GetObjectByMap/80           6386 ns         6386 ns       103811
BM_GetObjectByMap/96           8313 ns         8313 ns        84515
```

General object will not have too many data members, it seems slower if the count of members less than 32.

![image](https://user-images.githubusercontent.com/34831946/206891118-ba5c7d35-b772-4b10-878b-62cfc1e622a4.png)

```.cpp
#include <benchmark/benchmark.h>

#include <algorithm>
#include <forward_list>
#include <iostream>
#include <list>
#include <random>
#include <string>
#include <vector>

using Object = std::forward_list<std::string>;
using NameList = std::vector<std::string>;

std::string GenerateString() {
  std::seed_seq seq{time(0)};
  static std::default_random_engine gen{seq};
  std::uniform_int_distribution<size_t> distN(4, 15);
  std::uniform_int_distribution<unsigned char> distCh('a', 'z');
  std::string s(distN(gen), '\0');
  for (auto& ch : s) {
    ch = distCh(gen);
  }
  return s;
}

Object GenerateObject(size_t n) {
  Object obj;
  for (auto i = 0; i != 2 * n; ++i) {
    obj.emplace_front(GenerateString());
  }
  return obj;
}

NameList GetObjectNames(Object const& obj) {
  NameList names;
  for (auto it = obj.cbegin(); it != obj.cend(); ++it) {
    names.emplace_back(*it);
    if (++it == obj.cend()) {
      break;
    }
  }
  std::seed_seq seq{time(0)};
  static std::default_random_engine gen{seq};
  std::shuffle(names.begin(), names.end(), gen);
  return names;
}

void BM_GetObjectByIterate(benchmark::State& state) {
  auto object = GenerateObject(state.range(0));
  auto names = GetObjectNames(object);
  for (auto _ : state) {
    for (auto const& name : names) {
      std::string value;
      for (auto it = object.cbegin(), cend = object.cend(); it != cend; ++it) {
        if (name == *it) {
          if (++it != cend) {
            benchmark::DoNotOptimize(value = *it);
          }
        } else if (++it == cend) {
          break;
        }
      }  // for object
    }    // for name
  }      // for state
}

BENCHMARK(BM_GetObjectByIterate)
  ->DenseRange(1 << 1, 1 << 5, 1 << 3)
  ->DenseRange(1 << 5, 100, 1 << 4);

void BM_GetObjectByMap(benchmark::State& state) {
  auto object = GenerateObject(state.range(0));
  auto names = GetObjectNames(object);
  for (auto _ : state) {
    std::map<std::string_view, decltype(object.cend())> m;
    for (auto it = object.cbegin(), cend = object.cend(); it != cend; ++it) {
      auto name = it++;
      if (it == cend) {
        break;
      }
      m[name->c_str()] = it;
    }  // for object

    for (auto const& name : names) {
      std::string value;
      auto it = m.find(name);
      if (it != m.cend()) {
        benchmark::DoNotOptimize(value = *(it->second));
      }
    }  // for name
  }    // for state
}

BENCHMARK(BM_GetObjectByMap)
  ->DenseRange(1 << 1, 1 << 5, 1 << 3)
  ->DenseRange(1 << 5, 100, 1 << 4);
```

[link](https://quick-bench.com/q/EtcFmDAUAoMrPAVwiup7N8Vm108)

**Comment by yanminhui** [comment]
For searching object members only, it will be faster by ordered vector with binary search.

![image](https://user-images.githubusercontent.com/34831946/206904907-2656c109-5ed5-4bec-a4e1-e9d501943dd0.png)
[quick bench](https://quick-bench.com/q/cAJQx3yaetVoojOxFOavPBYXhlw)

```.cpp
void BM_GetObjectByVector(benchmark::State& state) {
  auto object = GenerateObject(state.range(0));
  auto names = GetObjectNames(object);
  for (auto _ : state) {
    std::vector<std::pair<std::string_view, decltype(object.cend())>> v;
    v.reserve(names.size());
    for (auto it = object.cbegin(), cend = object.cend(); it != cend; ++it) {
      auto name = it++;
      if (it == cend) {
        break;
      }
      v.emplace_back(*name, it);
    }  // for object
    std::sort(v.begin(), v.end(),
              [](auto const& a, auto const& b) { return a.first < b.first; });

    for (auto const& name : names) {
      std::string value;
      // binary search
      auto first = v.cbegin();
      auto last = v.cend();
      auto count = std::distance(first, last);
      while (count > 0) {
        auto it = first;
        auto step = count / 2;
        std::advance(it, step);
        auto cmp = it->first.compare(name);
        if (cmp == 0) {
          first = it;
          break;
        } else if (cmp < 0) {
          first = ++it;
          count -= step + 1;
        } else {
          count = step;
        }
      }
      if (first != last) {
        benchmark::DoNotOptimize(value = *(first->second));
      }
    }  // for name
  }    // for state
}

BENCHMARK(BM_GetObjectByVector)->RangeMultiplier(2)->Range(1 << 1, 1 << 12);
```

**Comment by xiegx94** [comment]
Hi, @yanminhui. Your benchmark has timed the cost of creating map. Actually, the purpose of creating multimap is for finding members may times. And, the important point is that creating a map is **optional**. We forgot updating `usage`, `FindMember` doesn't create map, you should call `CreateMap` firstly.

**Comment by yanminhui** [comment]
@xiegx94 

The benchmark is to test finding members many times and the cost of creating map is considered. `UpdateLazy` will call `CreateMap` always. 

Although creating map is optional, but user is hard to decide when to `CreateMap`.

Actually, the purpose of creating map is for finding members may times, `unordered_multimap` **O(1)** is better than `multimap` **O(logN)** in the case.

**Comment by xiegx94** [comment]
@liuq19

**Comment by xiegx94** [comment]
@liuq19

**Comment by xiegx94** [comment]
@yanminhui Sonic-cpp has provided memory pool allocator for multimap, which can enhance the performance of multimap.

**Comment by yanminhui** [comment]
> @yanminhui It's user's responsibility to decide when use `createmap`. If user concerns performance, they need benchmark with their workload.

It may be better to build map on demand during access object members.

For example:
```.cpp
sonic_force_inline MemberIterator findMemberImpl(StringView key) const {
  if (auto m = getMap()) [[likely]] {
    auto it = m->find(MSType(key.data(), key.size()));
    if (it != m->end()) {
      return memberBeginUnsafe() + it->second;
    }
    // don't return, try iterate object and update map object.
  } else if (this->Size() > kLimitsOfMap) {
    // TODO: ensure exists map object
  }

  // try iterate object and update map object.
  auto m = getMap();
  for (auto first = this->MemberEngin(), last = this->MemberEnd(); first != last; ++first) {
    if (m) {
      m->emplace(key, first); // TODO: update map object
    }
    if (first->name.GetStringView() == key) {
      return const_cast<MemberIterator>(first);
    }
  }
  return const_cast<MemberIterator>(this->MemberEnd());
}
```
> https://github.com/bytedance/sonic-cpp/blob/fc7545be5c393f0b43494111ea068e8fbac77065/include/sonic/dom/dynamicnode.h#L568-L584

**Comment by xiegx94** [comment]
> > @yanminhui It's user's responsibility to decide when use `createmap`. If user concerns performance, they need benchmark with their workload.
> 
> @xiegx94 It may be better to build map on demand during access object members.
> 
> For example:
> 
> ```c++
> sonic_force_inline MemberIterator findMemberImpl(StringView key) const {
>   if (auto m = getMap()) [[likely]] {
>     auto it = m->find(MSType(key.data(), key.size()));
>     if (it != m->end()) {
>       return memberBeginUnsafe() + it->second;
>     } else if (m.size() == this->Size()) { // all object members have been included in map.
>       return memberEndUnsafe();
>     }
>   } else if (this->Size() > kLimitsOfMap) {
>     // TODO: ensure exists map object
>   }
> 
>   // try iterate object and update map object.
>   auto m = getMap();
>   for (auto first = this->MemberBegin(), last = this->MemberEnd(); first != last; ++first) {
>     if (m) {
>       m->emplace(key, first); // TODO: update map object
>     }
>     if (first->name.GetStringView() == key) {
>       return const_cast<MemberIterator>(first);
>     }
>   }
>   return memberEndUnsafe();
> }
> ```
> 
> > https://github.com/bytedance/sonic-cpp/blob/fc7545be5c393f0b43494111ea068e8fbac77065/include/sonic/dom/dynamicnode.h#L568-L584

@yanminhui 
There are 2 problems:
- Create map need allocator to manger memory. FindMember API doesn't accept such argument.
- If user only need search one time, create map isn't a good idea for any size.

Default creating map has caused some performance problem in real workload.

**Comment by yanminhui** [comment]
> @yanminhui There are 2 problems:
> 
> * Create map need allocator to manger memory. FindMember API doesn't accept such argument.
> * If user only need search one time, create map isn't a good idea for any size.
> 
> Default creating map has caused some performance problem in real workload.

Offer another overload to implement different policy to help user.

```.cpp
ConstMemberIterator FindMember(Policy policy, StringView key, Allocator* alloc);
```

**Comment by liuq19** [comment]
> 

UpdateLazy 's optimization is mainly because parse ondemand, and CreateMap is not critical in the code. when json has many keys, createmap will be help.   And if not createmap here, it may be faster, but limited.

**Comment by liuq19** [comment]
> @xiegx94
> 
> The benchmark is to test finding members many times and the cost of creating map is considered. `UpdateLazy` will call `CreateMap` always.
> 
> Although creating map is optional, but user is hard to decide when to `CreateMap`.
> 
> Actually, the purpose of creating map is for finding members may times, `unordered_multimap` **O(1)** is better than `multimap` **O(logN)** in the case.

@yanminhui  UpdateLazy 's optimization is mainly because parse ondemand, and CreateMap is not critical in the code. when json has many keys, createmap will be help. And if not createmap here, it may be faster, but limited.

**Comment by liuq19** [comment]
> > @yanminhui There are 2 problems:
> > 
> > * Create map need allocator to manger memory. FindMember API doesn't accept such argument.
> > * If user only need search one time, create map isn't a good idea for any size.
> > 
> > Default creating map has caused some performance problem in real workload.
> 
> @xiegx94 Offer another overload to implement different policy to help user.
> 
> ```c++
> ConstMemberIterator FindMember(Policy policy, StringView key, Allocator* alloc);
> ```

@yanminhui  It sounds great. Maybe CreateMap(Policy, Alloctor) and FindMember(Policy, key) is an another choice. FindMember should not include any logic about creating the map.
