### ISSUE TITLE
doc.HasParseError()默认值赋值为true

### ISSUE THREAD

**Issue by 187nihao** [bytedance/sonic-cpp#49]
doc.HasParseError()的默认值建议赋值为true，doc.Parse(json)成功的时候赋值为false。因为有些情况，json为空就不存在pasre操作，doc引用返回给外部的时候，doc.HasParseError()为fasle（目前的默认值), 外界认为是doc初始化成功，后边doc.HasMember("xxx")就会core了

**Comment by liuq19** [comment]
感谢建议，后续会修复这个问题

**Comment by 187nihao** [comment]
你好：
      通过使用sonic库，今天又发现了一个bug, {"mfeat":{}} 这个json串，value为空，但是我如下操作会core


it_tmp 等于nullptr,但是m->value.MemberEnd() 不等于nullptr，但是严格起来，it_tmp 是需要等于 m->value.MemberEnd() 吧？ 这你们都测不出来吗？
这对使用者造成很大的麻烦！
麻烦尽快处理下，我去更新最新的版本

**Comment by 187nihao** [comment]
抱歉，理解错了,不是这个问题
















在 2023-02-06 14:44:58，"张军旗" ***@***.***> 写道：

你好：
      通过使用sonic库，今天又发现了一个bug, {"mfeat":{}} 这个json串，value为空，但是我如下操作会core


it_tmp 等于nullptr,但是m->value.MemberEnd() 不等于nullptr，但是严格起来，it_tmp 是需要等于 m->value.MemberEnd() 吧？ 这你们都测不出来吗？
这对使用者造成很大的麻烦！
麻烦尽快处理下，我去更新最新的版本
