### ISSUE TITLE
Core dumped without AVX2 instructiom (VM instance)

### ISSUE THREAD

**Issue by sweihub** [bytedance/sonic-cpp#50]
Yes, I know that sonic-cpp relies on the AVX2 instruction, for most VM instance, especially the cloud VMs, there's no AVX2 supported yet. But why the `simdjson` works normally? Can you fall back to sse/sse2 if no AVX2?

```
❯ ./build/benchmark/bench
[1]    2624172 illegal hardware instruction (core dumped)  ./build/benchmark/bench
```

CPU flags
```
❯ cat  /proc/cpuinfo | grep flags | uniq
```
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 ht syscall nx lm rep_good nopl xtopology cpuid tsc_known_freq pni cx16 x2apic hypervisor lahf_lm pti

**Comment by xiegx94** [comment]
You can compile your program using any architecture， but it will coredump when platform doesn't support such architecture。

SSE/NEON will be supported in future.

**Comment by liuq19** [comment]
Fixed it. sonic-cpp has supported only sse. https://github.com/bytedance/sonic-cpp/pull/56
