### ISSUE TITLE
为啥没有GetArray(),GetObject(),  原来rapidjson中的doc.GetArray(), doc.GetObject()怎么替换成sonic？

### ISSUE THREAD

**Issue by handsomeZWF** [bytedance/sonic-cpp#53]
content.AddMember("input_args", doc.GetArray(), a);          
rapidjson中的doc.GetArray() 怎么替换成sonic？  sonic中没有GetArray方法呀！

**Comment by handsomeZWF** [comment]
直接用AddMember(doc)就可以了

**Comment by Billy1900** [comment]
> 直接用AddMember(doc)就可以了

怎么用的？
